name: eniius

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, reopened, synchronize]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/cache@v3
        id: cache-mccode
        with:
          path: McCode
          key: McCode-git-cache
      - name: Clone McCode
        if: steps.cache-mccode.cache-hit != 'true'
        run: |
          if [ ! -d McCode ]; then
            git clone https://github.com/McStasMcXtrace/McCode --depth=1
          fi
      - uses: mamba-org/provision-with-micromamba@main
        with:
          environment-file: false
          environment-name: py38test
          cache-downloads: true
          extra-specs: |
            python=3.8
            numpy
            six
          channels: conda-forge
      - name: Build and test eniius
        run: |
          python setup.py bdist_wheel --universal
          pip install dist/*
          cd test
          python run_test.py
      - name: Upload release wheels
        if: ${{ github.event_name == 'release' }}
        run: |
          pip3 install requests
          python3 release.py --notest --github --token=${{ secrets.GH_TOKEN }}
      - uses: actions/upload-artifact@v3
        with:
          path: dist/*
